# Generated by Django 6.0.6 on 2026-07-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesastreNatural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TERREMOTO', 'Terremoto'), ('ERUPCAO', 'Erupção Vulcânica'), ('OUTRO', 'Outro')], default='TERREMOTO', max_length=20)),
                ('data_hora', models.DateTimeField(help_text='Data e hora do evento na Terra')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('magnitude', models.FloatField(blank=True, help_text='Magnitude do evento (ex: Escala Richter para terremotos)', null=True)),
                ('localizacao', models.CharField(help_text='Nome da região ou país do ocorrido', max_length=255)),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='EventoSolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(help_text='Data e hora do evento registrado')),
                ('indice_kp', models.FloatField(help_text='Índice Geomagnético Kp (vai de 0 a 9)')),
                ('velocidade_vento', models.FloatField(blank=True, help_text='Velocidade do vento solar em km/s', null=True)),
                ('tipo_alerta', models.CharField(blank=True, help_text='Classificação do alerta (ex: G1, G2, G3)', max_length=50, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
    ]
